### ISSUE TITLE
Erro ao iniciar 

### ISSUE THREAD

**Issue by vagners2** [rafaeldalbosco/juno_direct_checkout_flutter#3]
Olá,
estou recebendo o erro:
"Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter context"
A implementação está como no exemplo, somente com public_token modificado.

No debug o context, está nulo... 
![Screen Shot 2020-09-29 at 17 19 17](https://user-images.githubusercontent.com/10371828/94611419-15ccb380-0278-11eb-9378-41f1e328307d.png)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E287, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by rafaeldalbosco** [comment]
@vagners2 esse plugin é escrito em Java, me pareceu que você está mexendo no código nativo para um projeto em Kotlin. 
O plugin foi testado apenas em Java. 

Para utilizar no flutter primeiro é necessário inicializar chamando o método abaixo:

````
      var map = <String, dynamic>{
        "prod": false, //se quiser rodar em producao ou sandbox
        "public_token": "YOUR_PUBLIC_TOKEN" //passe o token desejado
      };
      print(await JunoDirectCheckout.init(map));
````

Nas suas dependências tente utilizar:

```
  juno_direct_checkout:
    git:
      url: https://github.com/rafaeldalbosco/juno_direct_checkout_flutter.git
```

**Comment by vagners2** [comment]
Fiz um pull-request do meu fork, identifiquei o problema e ajustei o pattern para receber a activity no construtor do plugin esse problema só ocorre nas novas versões do flutter onde o onAttachedToEngine não é mais usado.

**Comment by rafaeldalbosco** [comment]
Pull request aceito #4
